[package]
name = "tfbindiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
leb128 = "0.2.5"

object = "0.31.1"
cpp_demangle = "0.4.3"

thiserror = "1.0.48"
num_enum = "0.7.0"
iced-x86 = "1.20.0"
