[package]
name = "tfbindiff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
getopts = "0.2.21"
leb128 = "0.2.5"
num_enum = "0.7.0"
object = "0.31.1"
thiserror = "1.0.48"
